import { Transaction } from '../types';

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    date: '2024-04-01',
    amount: 5000,
    category: 'Salary',
    description: 'Monthly salary',
    type: 'income',
  },
  {
    id: '2',
    date: '2024-04-02',
    amount: 1200,
    category: 'Food',
    description: 'Grocery shopping',
    type: 'expense',
  },
  {
    id: '3',
    date: '2024-04-03',
    amount: 150,
    category: 'Transport',
    description: 'Gas and parking',
    type: 'expense',
  },
  {
    id: '4',
    date: '2024-04-05',
    amount: 500,
    category: 'Bills',
    description: 'Electricity bill',
    type: 'expense',
  },
  {
    id: '5',
    date: '2024-04-06',
    amount: 800,
    category: 'Entertainment',
    description: 'Concert tickets',
    type: 'expense',
  },
  {
    id: '6',
    date: '2024-04-08',
    amount: 120,
    category: 'Food',
    description: 'Restaurant',
    type: 'expense',
  },
  {
    id: '7',
    date: '2024-04-10',
    amount: 300,
    category: 'Travel',
    description: 'Flight booking',
    type: 'expense',
  },
  {
    id: '8',
    date: '2024-04-12',
    amount: 2500,
    category: 'Bonus',
    description: 'Performance bonus',
    type: 'income',
  },
  {
    id: '9',
    date: '2024-04-15',
    amount: 1500,
    category: 'Bills',
    description: 'Rent payment',
    type: 'expense',
  },
  {
    id: '10',
    date: '2024-04-18',
    amount: 200,
    category: 'Food',
    description: 'Food delivery',
    type: 'expense',
  },
  {
    id: '11',
    date: '2024-04-20',
    amount: 450,
    category: 'Health',
    description: 'Gym membership',
    type: 'expense',
  },
  {
    id: '12',
    date: '2024-04-22',
    amount: 600,
    category: 'Entertainment',
    description: 'Streaming subscriptions',
    type: 'expense',
  },
  {
    id: '13',
    date: '2024-04-25',
    amount: 1000,
    category: 'Travel',
    description: 'Hotel booking',
    type: 'expense',
  },
  {
    id: '14',
    date: '2024-04-28',
    amount: 300,
    category: 'Freelance',
    description: 'Project payment',
    type: 'income',
  },
  {
    id: '15',
    date: '2024-04-30',
    amount: 250,
    category: 'Food',
    description: 'Weekly groceries',
    type: 'expense',
  },
];

export const categoryColors: Record<string, string> = {
  Salary: '#ef4444',
  Bonus: '#f97316',
  Freelance: '#eab308',
  Food: '#22c55e',
  Transport: '#10b981',
  Bills: '#14b8a6',
  Entertainment: '#06b6d4',
  Travel: '#3b82f6',
  Health: '#8b5cf6',
};
